apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demoapp-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: registry.ng.bluemix.net/rmoe/demoapp:$TAG
        imagePullPolicy: Always
